[Variables]

;;Base Settings;;
Base=default
BaseStyle=none
HoneycombSize=90

;;Colors;;
;IconColor=76,86,106
;BaseColor=235,203,139
;ShadowColor=
;OverlayColor=
;ClearColor=

;;Hover Settings;;
Hover=default
HoverColor=0, 0, 0, 125

;;Misc Settings;;
;IconGreyscale=

;;Other Variables;;
Blank=#@#\Base\blank.png
Mono=#@#\Icons\#Type#\mono\#Icon#.png
MonoName=#@#\Icons\#Type#\mono\#IconMonoName#.png
Overlay=#@#\Icons\#Type#\overlay\#Icon#.png
@Include=#@#Variants/base_#Base#.inc

[Rainmeter]
Update=-1
