[Variables]

; After changing the variables, save the file (ctrl + S), 
; right click any Honeycomb and choose "Refresh HoneycombNG"

HoneycombSize=90

; Available bases:
; default | clear | mono
Base=default

; Available base styles:
; none | cube | glazed | gloss | gradient | jelly | oldios | toon-grad | toon
BaseStyle=none

; Available hover effects:
; default | clear | none | rim
Hover=default
HoverColor=0, 0, 0, 125

; Colors
; Remove the ; to enable the override

;IconColor=76,86,106
;BaseColor=235,203,139
;ShadowColor=
;OverlayColor=
;ClearColor=

; Misc options
;IconGreyscale=
